apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simpleserver3-pod
  name: simpleserver3-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleserver3-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simpleserver3-pod
    spec:
      containers:
      - image: amirhosseinbarikloo/simpleserver3
        name: simpleserver3
        resources: {}
        volumeMounts:
          - mountPath: /server_confige.config
            subPath: server_confige.config
            name: config-map
            readOnly: true
      volumes:
        - name: config-map
          configMap:
            name: server-config

status: {}
